Implemented display of curve transfinition points
ONEGOCH/BazisCAE.GUI pull request #105
Opened 2024-06-24 05:35 UTC by knsplm

Добавлен флажок и реализована подсветка точек после трансфиниции кривой.

2024-06-25 10:53 UTC, knsplm commented
Ссылка на gmsh api https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/api/gmshc.h?ref_type=heads

2024-06-26 07:47 UTC, ONEGOCH requested changes

2024-06-26 07:47 UTC, ONEGOCH commented on ModelModule/GMSHGeneralMeshControl.cs
> +                btnOK.Tag = new Dictionary<int, List<GeometryPoint>>();
А зачем свойству tag привязывать словарь Dictionary?

2024-06-26 07:47 UTC, ONEGOCH commented on ModelModule/GMSHGeneralMeshControl.cs
> +            if (btnOK.Tag != null)
Кажется что это лишняя проверка

2024-06-26 07:47 UTC, ONEGOCH commented on ModelModule/GMSHGeneralMeshControl.cs
> +                ObjectData.PointCollection.Add(gPoint);
Может быть раз это временные узлы не будем их хранить в  PointCollection? Может сразу закидывать на сцену?

2024-06-26 11:00 UTC, knsplm commented on ModelModule/GMSHGeneralMeshControl.cs
> +                ObjectData.PointCollection.Add(gPoint);
Учел все замечания

2024-07-01 10:47 UTC, closed without merging