92 добавление валидатора на различные строки ввода
ONEGOCH/BazisCAE.GUI pull request #106
Opened 2024-06-25 07:02 UTC by SherhUNV

2024-06-25 10:20 UTC, ONEGOCH requested changes
В продолжении разговора доработать валидатор. Добавить текстовое поле для регулярных выражений

2024-06-26 10:38 UTC, SherhUNV commented
> В продолжении разговора доработать валидатор. Добавить текстовое поле для регулярных выражений

Выполнено

2024-07-01 10:05 UTC, ONEGOCH requested changes
Привет. Давай может вынесем enum к месту реализации интерфейса.

2024-07-01 10:12 UTC, ONEGOCH approved these changes

2024-07-01 10:14 UTC, merged