86 расширение gui для экспорта сетки в формате stl
ONEGOCH/BazisCAE.GUI pull request #87
Opened 2024-05-08 10:11 UTC by SherhUNV

2024-05-21 07:14 UTC, ONEGOCH commented
По поводу реализации в  Result создал метод с заглушкой

    public class ResultsExporter : IResultsExporter
    {
        /// <inheritdoc/>
        public void ExportResults(IEnumerable<IResultFigure2D> figures, string savePath, string format)
        {
            throw new NotImplementedException();
        }
    }

2024-05-21 08:27 UTC, ONEGOCH requested changes

2024-05-21 08:27 UTC, ONEGOCH commented on GUI/BaseForm.cs
> +                    {
Это нужно реализовать в библиотеке Results. Я тебе создал класс и интерфейс. Перенеси это туда

2024-05-21 08:27 UTC, ONEGOCH commented on ResultModule/ResultPageSaverEventArgs.cs
> +        public ResultPage ResultPage { get; set; }
Передавать модуль через свойство не очень хорошая тенденция. Это обычно лается через объект. Аргументы при вызове события обычно такие: 
Событие (кто вызвал, какие аргументы)

2024-05-21 11:32 UTC, SherhUNV commented on ResultModule/ResultPageSaverEventArgs.cs
> +        public ResultPage ResultPage { get; set; }
да, я чуть подзабыл, что можно от отправителя в виде object определить настройки контроллера результатов

2024-05-22 11:50 UTC, SherhUNV commented on GUI/BaseForm.cs
> +                    {
Перенес, осталось обновить пакеты, чтобы в Bazis была актуальная версия ProjectInterface и экспорт будет работать

2024-05-27 05:48 UTC, ONEGOCH approved these changes

2024-05-27 05:50 UTC, merged